// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hensdtsgoarcmctqwfjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbnNkdHNnb2FyY21jdHF3ZmpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDY4NjgsImV4cCI6MjA2OTIyMjg2OH0.ETEGTj0pNimY1KGX_twe-pansFAr2jlYEJ-3hMoDy24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});